// Generated by 'unplugin-auto-import'
export {}
declare global {
  const useApp: typeof import('./src/core/hooks/useApp')['default']
  const useLoading: typeof import('./src/core/hooks/useLoading')['useLoading']
  const useModule: typeof import('./src/core/hooks/useModule')['default']
  const usePrecision: typeof import('./src/core/hooks/usePrecision')['default']
  const useRefs: typeof import('./src/core/hooks/useRefs')['useRefs']
  const useState: typeof import('./src/core/hooks/useState')['useState']
}
