export default {
    v1: {
        'color-scheme': 'light',
        '--el-color-white': '#ffffff',
        '--el-color-black': '#000000',
        '--el-color-primary': '#409eff',
        '--el-color-primary-light-3': '#79bbff',
        '--el-color-primary-light-5': '#a0cfff',
        '--el-color-primary-light-7': '#c6e2ff',
        '--el-color-primary-light-8': '#d9ecff',
        '--el-color-primary-light-9': '#ecf5ff',
        '--el-color-primary-dark-2': '#337ecc',
        '--el-color-success': '#67c23a',
        '--el-color-success-light-3': '#95d475',
        '--el-color-success-light-5': '#b3e19d',
        '--el-color-success-light-7': '#d1edc4',
        '--el-color-success-light-8': '#e1f3d8',
        '--el-color-success-light-9': '#f0f9eb',
        '--el-color-success-dark-2': '#529b2e',
        '--el-color-warning': '#e6a23c',
        '--el-color-warning-light-3': '#eebe77',
        '--el-color-warning-light-5': '#f3d19e',
        '--el-color-warning-light-7': '#f8e3c5',
        '--el-color-warning-light-8': '#faecd8',
        '--el-color-warning-light-9': '#fdf6ec',
        '--el-color-warning-dark-2': '#b88230',
        '--el-color-danger': '#f56c6c',
        '--el-color-danger-light-3': '#f89898',
        '--el-color-danger-light-5': '#fab6b6',
        '--el-color-danger-light-7': '#fcd3d3',
        '--el-color-danger-light-8': '#fde2e2',
        '--el-color-danger-light-9': '#fef0f0',
        '--el-color-danger-dark-2': '#c45656',
        '--el-color-error': '#f56c6c',
        '--el-color-error-light-3': '#f89898',
        '--el-color-error-light-5': '#fab6b6',
        '--el-color-error-light-7': '#fcd3d3',
        '--el-color-error-light-8': '#fde2e2',
        '--el-color-error-light-9': '#fef0f0',
        '--el-color-error-dark-2': '#c45656',
        '--el-color-info': '#909399',
        '--el-color-info-light-3': '#b1b3b8',
        '--el-color-info-light-5': '#c8c9cc',
        '--el-color-info-light-7': '#dedfe0',
        '--el-color-info-light-8': '#e9e9eb',
        '--el-color-info-light-9': '#f4f4f5',
        '--el-color-info-dark-2': '#73767a',
        '--el-bg-color': '#ffffff',
        '--el-bg-color-page': '#f2f3f5',
        '--el-bg-color-overlay': '#ffffff',
        '--el-text-color-primary': '#303133',
        '--el-text-color-regular': '#606266',
        '--el-text-color-secondary': '#909399',
        '--el-text-color-placeholder': '#a8abb2',
        '--el-text-color-disabled': '#c0c4cc',
        '--el-border-color': '#dcdfe6',
        '--el-border-color-light': '#e4e7ed',
        '--el-border-color-lighter': '#ebeef5',
        '--el-border-color-extra-light': '#f2f6fc',
        '--el-border-color-dark': '#d4d7de',
        '--el-border-color-darker': '#cdd0d6',
        '--el-fill-color': '#f0f2f5',
        '--el-fill-color-light': '#f5f7fa',
        '--el-fill-color-lighter': '#fafafa',
        '--el-fill-color-extra-light': '#fafcff',
        '--el-fill-color-dark': '#ebedf0',
        '--el-fill-color-darker': '#e6e8eb',
        '--el-fill-color-blank': '#ffffff',
        '--el-box-shadow': '0px 12px 32px 4px rgba(0, 0, 0, 0.04),0px 8px 20px rgba(0, 0, 0, 0.08)',
        '--el-box-shadow-light': '0px 0px 12px rgba(0, 0, 0, 0.12)',
        '--el-box-shadow-lighter': '0px 0px 6px rgba(0, 0, 0, 0.12)',
        '--el-box-shadow-dark': '0px 16px 48px 16px rgba(0, 0, 0, 0.08),0px 12px 32px rgba(0, 0, 0, 0.12),0px 8px 16px -8px rgba(0, 0, 0, 0.16)',
        '--el-disabled-bg-color': 'var(--el-fill-color-light)',
        '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
        '--el-disabled-border-color': 'var(--el-border-color-light)',
        '--el-overlay-color': 'rgba(0, 0, 0, 0.8)',
        '--el-overlay-color-light': 'rgba(0, 0, 0, 0.7)',
        '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.5)',
        '--el-mask-color': 'rgba(255, 255, 255, 0.9)',
        '--el-mask-color-extra-light': 'rgba(255, 255, 255, 0.3)',
        '--el-border-width': '1px',
        '--el-border-style': 'solid',
        '--el-border-color-hover': 'var(--el-text-color-disabled)',
        '--el-border': 'var(--el-border-width) var(--el-border-style) var(--el-border-color)',
        '--el-svg-monochrome-grey': 'var(--el-border-color)',
    },
    v2: {
        'color-scheme': 'light',
        '--el-color-white': '#ffffff',
        '--el-color-black': '#000000',
        '--el-color-primary': '#126bae',
        '--el-color-primary-light-3': '#5997c6',
        '--el-color-primary-light-5': '#89b5d7',
        '--el-color-primary-light-7': '#b8d3e7',
        '--el-color-primary-light-8': '#d0e1ef',
        '--el-color-primary-light-9': '#e7f0f7',
        '--el-color-primary-dark-2': '#0e568b',
        '--el-color-success': '#45b787',
        '--el-color-success-light-3': '#7dcdab',
        '--el-color-success-light-5': '#a2dbc3',
        '--el-color-success-light-7': '#c7e9db',
        '--el-color-success-light-8': '#daf1e7',
        '--el-color-success-light-9': '#ecf8f3',
        '--el-color-success-dark-2': '#37926c',
        '--el-color-warning': '#fa7e23',
        '--el-color-warning-light-3': '#fca565',
        '--el-color-warning-light-5': '#fdbf91',
        '--el-color-warning-light-7': '#fed8bd',
        '--el-color-warning-light-8': '#fee5d3',
        '--el-color-warning-light-9': '#fff2e9',
        '--el-color-warning-dark-2': '#c8651c',
        '--el-color-danger': '#ed3333',
        '--el-color-danger-light-3': '#f27070',
        '--el-color-danger-light-5': '#f69999',
        '--el-color-danger-light-7': '#fac2c2',
        '--el-color-danger-light-8': '#fbd6d6',
        '--el-color-danger-light-9': '#fdebeb',
        '--el-color-danger-dark-2': '#be2929',
        '--el-color-error': '#ed3333',
        '--el-color-error-light-3': '#f27070',
        '--el-color-error-light-5': '#f69999',
        '--el-color-error-light-7': '#fac2c2',
        '--el-color-error-light-8': '#fbd6d6',
        '--el-color-error-light-9': '#fdebeb',
        '--el-color-error-dark-2': '#be2929',
        '--el-color-info': '#909399',
        '--el-color-info-light-3': '#b1b3b8',
        '--el-color-info-light-5': '#c8c9cc',
        '--el-color-info-light-7': '#dedfe0',
        '--el-color-info-light-8': '#e9e9eb',
        '--el-color-info-light-9': '#f4f4f5',
        '--el-color-info-dark-2': '#73767a',
        '--el-bg-color': '#ffffff',
        '--el-bg-color-page': '#f2f3f5',
        '--el-bg-color-overlay': '#ffffff',
        '--el-text-color-primary': '#303133',
        '--el-text-color-regular': '#606266',
        '--el-text-color-secondary': '#909399',
        '--el-text-color-placeholder': '#a8abb2',
        '--el-text-color-disabled': '#c0c4cc',
        '--el-border-color': '#dcdfe6',
        '--el-border-color-light': '#e4e7ed',
        '--el-border-color-lighter': '#ebeef5',
        '--el-border-color-extra-light': '#f2f6fc',
        '--el-border-color-dark': '#d4d7de',
        '--el-border-color-darker': '#cdd0d6',
        '--el-fill-color': '#f0f2f5',
        '--el-fill-color-light': '#f5f7fa',
        '--el-fill-color-lighter': '#fafafa',
        '--el-fill-color-extra-light': '#fafcff',
        '--el-fill-color-dark': '#ebedf0',
        '--el-fill-color-darker': '#e6e8eb',
        '--el-fill-color-blank': '#ffffff',
        '--el-box-shadow': '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
        '--el-box-shadow-light': '0px 0px 12px rgba(0, 0, 0, 0.12)',
        '--el-box-shadow-lighter': '0px 0px 6px rgba(0, 0, 0, 0.12)',
        '--el-box-shadow-dark': '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12), 0px 8px 16px -8px rgba(0, 0, 0, 0.16)',
        '--el-disabled-bg-color': 'var(--el-fill-color-light)',
        '--el-disabled-text-color': 'var(--el-text-color-placeholder)',
        '--el-disabled-border-color': 'var(--el-border-color-light)',
        '--el-overlay-color': 'rgba(0, 0, 0, 0.8)',
        '--el-overlay-color-light': 'rgba(0, 0, 0, 0.7)',
        '--el-overlay-color-lighter': 'rgba(0, 0, 0, 0.5)',
        '--el-mask-color': 'rgba(255, 255, 255, 0.9)',
        '--el-mask-color-extra-light': 'rgba(255, 255, 255, 0.3)',
        '--el-border-width': '1px',
        '--el-border-style': 'solid',
        '--el-border-color-hover': 'var(--el-text-color-disabled)',
        '--el-border': 'var(--el-border-width) var(--el-border-style) var(--el-border-color)',
        '--el-svg-monochrome-grey': 'var(--el-border-color)',
    },
};
